export {default as LossChart} from "./LossChart.vue"
export {default as MostPlayedChart} from "./MostPlayedChart.vue"
export {default as MostEloChart} from "./MostEloChart.vue"
export {default as EloRangeChart} from "./EloRangeChart.vue"
export {default as PointDiffChart} from "./PointDiffChart.vue"
// export {default as Chart} from "./Chart.vue"
