export { default as MatchCard } from "./MatchCard.vue";
export { default as MostPlayedCard } from "./MostPlayedCard.vue";
export { default as EloGainsCard } from "./EloGainsCard.vue";
export { default as GoodBadCard } from "./GoodBadCard.vue";
export { default as AverageOpponentCard } from "./AverageOpponentCard.vue";
export { default as UniqueOpponentCard } from "./UniqueOpponentCard.vue";
export { default as HighestOpponentCard } from "./HighestOpponentCard.vue";
export { default as HighestNowCard } from "./HighestNowCard.vue";
export { default as LowestOpponentCard } from "./LowestOpponentCard.vue";
export { default as LowestNowCard } from "./LowestNowCard.vue";
export { default as MostPlayedOpponentsCard } from "./MostPlayedOpponentsCard.vue";
export { default as MostImprovedCard } from "./MostImprovedCard.vue";
export { default as MostDeclinedCard } from "./MostDeclinedCard.vue";
export { default as EloTakenCard } from "./EloTakenCard.vue";
export { default as SetInfoCard } from "./SetInfoCard.vue";
export { default as RoundsBeyondCard } from "./RoundsBeyondCard.vue";
export { default as FastWinCard } from "./FastWinCard.vue";
export { default as ComebackCard } from "./ComebackCard.vue";
export { default as SetPointsCard } from "./SetPointsCard.vue";
export { default as MatchPointsCard } from "./MatchPointsCard.vue";
export { default as LongestRoundCard } from "./LongestRoundCard.vue";
export {default as StreakCard} from "./StreakCard.vue";
// export {default as Card} from "./Card.vue";
